name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Clean and install dependencies
      run: |
        rm -rf node_modules package-lock.json
        npm install

    - name: Check Jest version
      run: npx jest --version

    - name: Run tests
      run: npx jest
